"""PM-framework analysis sections schema.

Three structured sections always generated by WriterAgent:
- MarketBackground: market context, trends, drivers, challenges
- FeatureInsights: table-stakes, differentiators, gaps across competitors
- OperationMonetization: GTM profiles, AARRR funnel notes
"""

from pydantic import BaseModel, Field


class MarketTrend(BaseModel):
    trend: str
    evidence: list[str] = Field(default_factory=list)  # source_ids


class MarketBackground(BaseModel):
    market_overview: str = ""
    market_size_notes: str = ""  # TAM/SAM estimates or qualitative description
    trends: list[MarketTrend] = Field(default_factory=list)
    key_drivers: list[str] = Field(default_factory=list)
    key_challenges: list[str] = Field(default_factory=list)


class FeatureInsights(BaseModel):
    table_stakes: list[str] = Field(default_factory=list)
    differentiators: list[dict] = Field(default_factory=list)  # [{feature, competitors:[]}]
    gaps: list[str] = Field(default_factory=list)
    cross_competitor_patterns: list[str] = Field(default_factory=list)


class GtmProfile(BaseModel):
    competitor_name: str
    motion: str = ""  # PLG | sales_led | marketing_led | channel | hybrid
    acquisition_channels: list[str] = Field(default_factory=list)
    pricing_strategy: str = ""  # freemium | per_seat | usage_based | flat_rate | enterprise
    expansion_model: str = ""
    evidence: list[str] = Field(default_factory=list)


class OperationMonetization(BaseModel):
    gtm_profiles: list[GtmProfile] = Field(default_factory=list)
    monetization_patterns: list[str] = Field(default_factory=list)
    aarrr_notes: dict = Field(default_factory=dict)  # {stage: {competitor: notes}}
